# docker-compose.training.yml
version: '3.8'
services:
  pytorch-training:
    image: nvcr.io/nvidia/pytorch:25.02-py3
    volumes:
      - ./data:/data
      - ./models:/models
      - ./scripts:/scripts
    command: python /scripts/finetune_model.py
    environment:
      - QUANTIZATION_LEVEL=Q4_K_M