# docker/ai-infrastructure/training-layer/docker-compose.yml
version: '3.8'

services:
  model-utils:
    image: nvcr.io/eevaigoeixww/conversational-ai/model-utils:4.0.0
    container_name: training-model-utils
    volumes:
      - ./data:/data
      - ./models:/models
      - ./config:/config
    ports:
      - "8501:8501"  # For potential UI access
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]